command: ["python", "app.py"]

# Environment variables
env:
  - name: "SECRET_SCOPE"
    value: "slackbot-4"
  - name: "GENIE_SPACE_ID"
    value: "01f060f6a88d1f51841b3a51774f6dc6"
  - name: "SHOW_SQL_QUERY"
    value: "true"